### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../../data/processed_amass_same_shape_seq/Eyes_Japan_Dataset/aita/accident-08-damage rightfoot-aita_poses_719_frames_30_fps.npz'

### ISSUE THREAD

**Issue by unparalleled-soul** [lijiaman/egoego_release#7]
I executed the instruction ：python extract_amass_motion_for_ares.py
Traceback (most recent call last):
  File "extract_amass_motion_for_ares.py", line 60, in <module>
    read_motion_from_habitat(amass_data_folder, habitat_folder, extract_index_pkl_path)
  File "extract_amass_motion_for_ares.py", line 37, in read_motion_from_habitat
    ori_npz_data = np.load(ori_data_path, allow_pickle=True)
  File "/data1/miniconda3/envs/egoego_env/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '../../data/processed_amass_same_shape_seq/Eyes_Japan_Dataset/aita/accident-08-damage rightfoot-aita_poses_719_frames_30_fps.npz'
But I only have this file named "accident-08-damage rightfoot-aita_poses_720_frames_30_fps.npz" in my folder.
Could you please guide me on how to resolve this issue? Are there specific steps or dependencies that I may have missed?
Thank you for your assistance in advance.

**Comment by PX-Xu** [comment]
Hello guy. I have the same question as you. Do you solve this problem? 
Hope your reply. Thanks.

**Comment by avegetablechicken** [comment]
have to fix unpaired frames in file name:
```python
ori_data_path = os.path.join(amass_ori_folder, curr_seq_data['path'])
try:
    ori_npz_data = np.load(ori_data_path, allow_pickle=True) 
except Exception:
    dir_name, file_name = os.path.split(ori_data_path)
    
    match = re.match(r"(.*_)(\d+)(_frames_.*)", file_name)
    if not match:
        print(f"Error: {ori_data_path}")
        with open('missed_amass_seqs.txt', 'a') as f:
            f.write(ori_data_path + '\n')
        continue
    
    prefix, frames, suffix = match.groups()
    found = False
    for f in os.listdir(dir_name):
        if f.startswith(prefix) and f.endswith(suffix) and f != file_name:
            ori_data_path = os.path.join(os.path.join(dir_name, f))
            ori_npz_data = np.load(ori_data_path, allow_pickle=True) 
            found = True
            break
    if not found:
        print(f"Unmatched: {ori_data_path}")
        with open('missed_amass_seqs.txt', 'a') as f:
            f.write(ori_data_path + '\n')
        continue
```
When it comes to my AMASS-SMPLHG datasets, still there are 8 unmatched files:
data/processed_amass_same_shape_seq/Eyes_Japan_Dataset/takiguchi/jump-06-rope normal run fast-takiguchi_poses_599_frames_30_fps.npz
data/processed_amass_same_shape_seq/CMU/143/143_38_poses_526_frames_30_fps.npz
data/processed_amass_same_shape_seq/Eyes_Japan_Dataset/ichige/jump-13-matrix-ichige_poses_719_frames_30_fps.npz
data/processed_amass_same_shape_seq/MPI_mosh/50004/misc 1_poses_305_frames_30_fps.npz
data/processed_amass_same_shape_seq/Eyes_Japan_Dataset/aita/accident-09-damage leftfoot-aita_poses_719_frames_30_fps.npz
data/processed_amass_same_shape_seq/KIT/424/step_stones01_poses_339_frames_30_fps.npz
data/processed_amass_same_shape_seq/Eyes_Japan_Dataset/takiguchi/jump-05-rope normal run-takiguchi_poses_595_frames_30_fps.npz
data/processed_amass_same_shape_seq/Eyes_Japan_Dataset/kudo/gesture_etc-41-mosh-kudo_poses_791_frames_30_fps.npz
